name: Reusable haskell build workflow

on:
  workflow_call:
    # https://github.com/orgs/community/discussions/11692
    inputs:
      matrix-ghc:
        required: true
        type: string
      matrix-os:
        required: true
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghc: ${{ fromJson(inputs.matrix-ghc) }}
        os: ${{ fromJson(inputs.matrix-os) }}
    runs-on: ${{ matrix.os }}

    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.10.3.0'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      # We don't run hlint tests, because different versions of hlint have different suggestions, and we don't want to worry about satisfying them all.
      run: cabal test --enable-tests -f-hlint all

    - if: matrix.ghc != '8.4.4'
      # docs aren't built on ghc 8.4.4 because some dependency docs don't build on older GHCs
      name: Build Docs
      run: cabal haddock
